In [1]:
import re
import numpy as np
def dms2dd(degrees, minutes, seconds, direction):
    dd = float(degrees) + float(minutes)/60 + float(seconds)/(60*60);
    if direction == 'E' or direction == 'N':
        dd *= -1
    return dd;

def dd2dms(deg):
    d = int(deg)
    md = abs(deg - d) * 60
    m = int(md)
    sd = (md - m) * 60
    return [d, m, sd]

def parse_dms(dms):
    parts = re.split('-', dms)
    lat = dms2dd(parts[0], parts[1], parts[2], parts[3])

    return (lat)

dd = parse_dms("01-17-07.00000-N")

#print(dd)

In [2]:
f=open('LatLongSing.txt',"+r").readlines()

In [3]:
CoordsDMS=[[line.split(' ')[4:][0]]+[line.split(' ')[4:][1][:-1]] for line in f]

In [4]:

deg_lat=np.asarray([parse_dms(Coords[0]) for Coords in CoordsDMS])
deg_long=np.asarray([parse_dms(Coords[1]) for Coords in CoordsDMS])

In [5]:
deg=np.dstack([deg_lat,deg_long])[0]

In [6]:
deg

array([[  -1.28527778, -103.81133333],
       [  -1.26504155, -103.82904053],
       [  -1.28941141, -103.8256073 ],
       [  -1.29558965, -103.7562561 ],
       [  -1.34226917, -103.79608154],
       [  -1.28048727, -103.86474609],
       [  -1.24684982, -103.84380341],
       [  -1.293187  , -103.89015198],
       [  -1.33265876, -103.89083862],
       [  -1.3669815 , -103.8558197 ],
       [  -1.34982019, -103.73497009],
       [  -1.23037418, -103.76586914],
       [  -1.22076334, -103.85375977],
       [  -1.30314081, -104.01237488],
       [  -1.42670191, -103.87641907],
       [  -1.15760556, -103.88671875],
       [  -1.29696259, -103.73291016]])

In [7]:
# Python 3 program to calculate Distance Between Two Points on Earth 
from math import radians, cos, sin, asin, sqrt 
def AngDist(lat1, lat2, lon1, lon2): 
# The math module contains a function named 
# radians which converts from degrees to radians. 
    lon1 = radians(lon1) 
    lon2 = radians(lon2) 
    lat1 = radians(lat1) 
    lat2 = radians(lat2) 
# Haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2

    c = 2 * asin(sqrt(a)) 
    
    return(c*180/(np.pi)) 

In [8]:
distsInDegs=np.asarray([AngDist(deg[0][0],deg[i][0],deg[0][1],deg[i][1]) for i in range(1,len(deg))])
#np.size(distsInDegs)

In [9]:
np.argsort(distsInDegs)

array([ 1,  0,  5,  4,  2,  3, 10, 11,  6, 15,  7,  8,  9, 14, 13, 12],
      dtype=int64)

In [10]:
#print([deg[:,0],deg[:,1]])
dist_compile=np.dstack([deg[0:16,0],deg[0:16,1],distsInDegs])

In [11]:
dist_compile[0]

array([[-1.28527778e+00, -1.03811333e+02,  2.68866929e-02],
       [-1.26504155e+00, -1.03829041e+02,  1.48569927e-02],
       [-1.28941141e+00, -1.03825607e+02,  5.60205099e-02],
       [-1.29558965e+00, -1.03756256e+02,  5.89958803e-02],
       [-1.34226917e+00, -1.03796082e+02,  5.36138230e-02],
       [-1.28048727e+00, -1.03864746e+02,  5.03040637e-02],
       [-1.24684982e+00, -1.03843803e+02,  7.91946316e-02],
       [-1.29318700e+00, -1.03890152e+02,  9.25351234e-02],
       [-1.33265876e+00, -1.03890839e+02,  9.30240583e-02],
       [-1.36698150e+00, -1.03855820e+02,  9.99699147e-02],
       [-1.34982019e+00, -1.03734970e+02,  7.12769377e-02],
       [-1.23037418e+00, -1.03765869e+02,  7.72091584e-02],
       [-1.22076334e+00, -1.03853760e+02,  2.01782485e-01],
       [-1.30314081e+00, -1.04012375e+02,  1.55674539e-01],
       [-1.42670191e+00, -1.03876419e+02,  1.48258461e-01],
       [-1.15760556e+00, -1.03886719e+02,  7.92692065e-02]])

In [12]:
import numpy as np

In [13]:
np.sin(np.pi/2.-(np.pi/180.)*deg[0][0])

0.9997484058579017

In [14]:
np.sin(np.pi/2.-(np.pi/180.)*deg[:,0])

array([0.99974841, 0.99975627, 0.99974678, 0.99974435, 0.9997256 ,
       0.99975028, 0.99976322, 0.9997453 , 0.99972952, 0.9997154 ,
       0.9997225 , 0.99976944, 0.99977303, 0.99974136, 0.99968999,
       0.99979591, 0.99974381])